<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" encoding="UTF-8" indent="yes"/>

    <!-- Main template for mockup XML -->
    <xsl:template match="/mockupPrototype">
        <html lang="en">
        <head>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title><xsl:value-of select="title"/></title>
            <link rel="stylesheet" href="styles.css"/>
        </head>
        <body>
            <div class="aicoe-header">
                <h1>AICOE Interactive Prototype</h1>
                <p><xsl:value-of select="description"/></p>
            </div>

            <nav class="navigation">
                <xsl:for-each select="screens/screen">
                    <a href="#{generate-id(.)}" class="nav-link">
                        <xsl:value-of select="title"/>
                    </a>
                </xsl:for-each>
            </nav>

            <div class="screens">
                <xsl:for-each select="screens/screen">
                    <section id="{generate-id(.)}" class="screen">
                        <h2><xsl:value-of select="title"/></h2>
                        <div class="screen-content">
                            <xsl:value-of select="content" disable-output-escaping="yes"/>
                        </div>
                    </section>
                </xsl:for-each>
            </div>

            <div class="aicoe-footer">
                <p>Prototype generated by AICOE Platform</p>
            </div>
        </body>
        </html>
    </xsl:template>
</xsl:stylesheet>